### ISSUE TITLE
quick_sort_recursive is naive

### ISSUE THREAD

**Issue by Moeologist** [Qv2ray/shadowsocksr-uvw#14]
感谢开发者们的付出
https://github.com/Qv2ray/shadowsocksr-uvw/blob/ae98821326b17c2f603556f0dc77197dbcec6388/src/obfs/auth_chain.c#L25
处的quick_sort实现过于naive。
而且后面两行使用了中文注释，会导致msvc报不明所以的错误。需要加上/utf-8的CFLAG

**Comment by darsvador** [comment]
![删掉了](https://github.com/Qv2ray/shadowsocksr-uvw/commit/e0d1a52d718f75becdb5a966183836517048bfbf)
