### ISSUE TITLE
请问一下 Build 之后如何安装？

### ISSUE THREAD

**Issue by sixg0000d** [Qv2ray/shadowsocksr-uvw#15]
- 系统环境:
  - 发行版： Fedora 32 x86_64
  - cmake版本： cmake version 3.17.4
  - gnu make版本： GNU Make 4.2.1

我按照 README 中的步骤，使用系统中的 `libuv` 和 `libsodium` 构建：
```shell
mkdir build
cd build
cmake .. -DSSR_UVW_WITH_QT=0 -DUSE_SYSTEM_SODIUM=ON -DUSE_SYSTEM_LIBUV=ON -DSTATIC_LINK_LIBUV=OFF -DSTATIC_LINK_SODIUM=OFF
make
```

然后尝试使用 make 安装：
```
$ make install
make: *** 没有规则可制作目标“install”。 停止。
```
尝试使用 cmake 安装：
```
$ cmake --install . --prefix ../root
-- Install configuration: ""
```

（libshadowsocksr-uvw.a 和 ssr-local 已经在 build/src 下产生了，我能够手动安装。但实际上我想尝试将 shadowsocksr-uvw 打包成 rpm，使用手动安装的话对于打包来说会有点麻烦）

**Comment by sixg0000d** [comment]
还有请教一下使用这种方法构建的 shadowsocksr-uvw 在运行时需要哪些依赖？
libuv libsodium openssl 这三个库都需要吗？

**Comment by darsvador** [comment]
> make install 失败

额,由于现在没有写install规则, 安装失败是预期现象.  我可以加一下, install `ssr-local`.


> -DUSE_SYSTEM_SODIUM=ON -DUSE_SYSTEM_LIBUV=ON -DSTATIC_LINK_LIBUV=OFF -DSTATIC_LINK_SODIUM=OFF

这个意味着运行时需要libuv (>=v1.38), Libsodium, OpenSSL三个库. 
最小依赖就是默认的选项,静态链接libuv和libsodium,运行时依赖OpenSSL.

**Comment by sixg0000d** [comment]
> > make install 失败
> 
> 额,由于现在没有写install规则, 安装失败是预期现象. 我可以加一下, install `ssr-local`.
> 
> > -DUSE_SYSTEM_SODIUM=ON -DUSE_SYSTEM_LIBUV=ON -DSTATIC_LINK_LIBUV=OFF -DSTATIC_LINK_SODIUM=OFF
> 
> 这个意味着运行时需要libuv (>=v1.38), Libsodium, OpenSSL三个库.
> 最小依赖就是默认的选项,静态链接libuv和libsodium,运行时依赖OpenSSL.

好的，谢谢

**Comment by darsvador** [comment]
https://github.com/Qv2ray/shadowsocksr-uvw/commit/b7d68313fc978718d8629af66b343e570784df10 @sixg0000d 你可以看一下满足不满足打包的需要,目前会默认在 `CMAKE_INSTALL_PREFIX/bin`目录下安装`ssr-local`

**Comment by sixg0000d** [comment]
> https://github.com/Qv2ray/shadowsocksr-uvw/commit/b7d68313fc978718d8629af66b343e570784df10 @sixg0000d 你可以看一下满足不满足打包的需要,目前会默认在 `CMAKE_INSTALL_PREFIX/bin`目录下安装`ssr-local`

其实之前没有 install 规则也能满足打包需要，只是容易出错，现在有了 install 规则打包应该更容易了。总而言之，谢谢！

已经打包成功了：
[sixg0000d/shadowsocksr-uvw](https://copr.fedorainfracloud.org/coprs/sixg0000d/shadowsocksr-uvw/)
