### ISSUE TITLE
replace std::localtime to avoid race conditions

### ISSUE THREAD

**Issue by DuckSoft** [Qv2ray/shadowsocksr-uvw#5]
https://github.com/Qv2ray/shadowsocksr-uvw/blob/0eaaf04df2d472e4a53c20c4b3fbb80c23e87b09/src/ssrutils.h#L98

https://github.com/Qv2ray/shadowsocksr-uvw/blob/0eaaf04df2d472e4a53c20c4b3fbb80c23e87b09/src/ssrutils.h#L110

https://github.com/Qv2ray/shadowsocksr-uvw/blob/0eaaf04df2d472e4a53c20c4b3fbb80c23e87b09/src/ssrutils.h#L123

https://github.com/Qv2ray/shadowsocksr-uvw/blob/0eaaf04df2d472e4a53c20c4b3fbb80c23e87b09/src/ssrutils.h#L134

https://github.com/Qv2ray/shadowsocksr-uvw/blob/0eaaf04df2d472e4a53c20c4b3fbb80c23e87b09/src/ssrutils.h#L152

https://github.com/Qv2ray/shadowsocksr-uvw/blob/0eaaf04df2d472e4a53c20c4b3fbb80c23e87b09/src/ssrutils.h#L162

https://github.com/Qv2ray/shadowsocksr-uvw/blob/0eaaf04df2d472e4a53c20c4b3fbb80c23e87b09/src/ssrutils.h#L203

https://github.com/Qv2ray/shadowsocksr-uvw/blob/0eaaf04df2d472e4a53c20c4b3fbb80c23e87b09/src/ssrutils.h#L226

Ref: https://wiki.sei.cmu.edu/confluence/display/c/CON33-C.+Avoid+race+conditions+when+using+library+functions

**Comment by darsvador** [comment]
> https://stackoverflow.com/questions/48106291/will-getting-the-current-date-time-be-thread-safe-in-c20

> https://stackoverflow.com/questions/25618702/why-is-there-no-c11-threadsafe-alternative-to-stdlocaltime-and-stdgmtime
